version: "3"
services:
  nginx:
    image: nginx:1.15.7-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./:/var/www/html/:rw
      - ./docker/conf/conf.d:/etc/nginx/conf.d/:rw
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/log/nginx:/var/log/nginx/:rw
    restart: always
    depends_on:
      - php
    networks:
      - default

  php:
    build:
      context: .
      args:
        PHP_VERSION: 7.2.19
        ALPINE_REPOSITORIES: mirrors.aliyun.com
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}

    volumes:
      - ./:/var/www/html/:rw
      - ./docker/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./docker/log/php:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - rabbitmq
    ports:
      - ${PHP_PORT}:8282
    networks:
      - default

  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./docker/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./docker/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:5.0.3-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/conf/redis.conf:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default

  rabbitmq:
    image: rabbitmq:management
    restart: always
    networks:
      - default
    ports:
      - ${RABBITMQ_C_PORT}:5672
      - ${RABBITMQ_S_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

networks:
  default:
